# Ejercicios Numpy para practicar...
Recuerda las redes neuronales no son mas que matrices y más matrices.


Realiza cada uno de estos ejercicios para comprobar tu nivel.

#### 1. importa el package numpy como  `np` 

In [2]:
import numpy as np

print(np.__name__)
print(np.__version__)
a=np.sum([1, 2])
print(a)

numpy
1.16.4
3


#### 2. Imprimir versión y configuración 

In [10]:
print(np.__version__)
print(np.__config__)

1.16.4
<module 'numpy.__config__' from '/home/alvaro/Escritorio/UNI/Clase/CompuBioInspirada/anaconda3/lib/python3.7/site-packages/numpy/__config__.py'>


#### 3. Crear un vector vacio de tamaño 10

In [11]:
array = np.empty(10)
print (array.size)

10


#### 4.  imprime el tamaño de memoria en bytes de un array de 10x10 del tipo que quieras

In [20]:
array = np.empty((10,10), dtype=int)
print (array.nbytes)

array = np.zeros((10,10), dtype=int)
print (array)

800
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 5. Saca en linea la documentación de la funcion add

In [14]:
np.add?

#### 6.  Dado un vector de 20 elementos a nulo, haz que el 10, 15 y 20 tomen valor 10 

In [24]:
array = np.empty(20)
array[9] = 10 
array[14] = 10 
array[19] = 10
#se puede hacer en una linea

#### 7.  Crea un vector con valores entre 10 y 49 de dos en dos

In [26]:
np.arange(10, 49, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### 8. Haz que se asigne en orden inverso e  imprimelo 

In [29]:
np.arange(49, 10, -2)

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17,
       15, 13, 11])

#### 9.  Crea una matriz de 3x3 con valores en el rango de 0..8

In [30]:
np.random.randint(0, 8, (3, 3))

array([[5, 3, 3],
       [4, 0, 5],
       [2, 7, 7]])

#### 10.Dado el siguiente vector \[1,2,0,0,4,0\] busca los indices que contienen valores distintos de 0

In [35]:
np.array[1,2,0,0,4,0]

TypeError: 'builtin_function_or_method' object is not subscriptable

#### 11. crea una matriz identidad de 3x3

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Crea una matriz de 3x3x3 con valores aleatorios

In [10]:
np.random.randint(10, size=(3, 3, 3))

array([[[2, 1, 6],
        [5, 7, 7],
        [6, 2, 1]],

       [[7, 0, 3],
        [0, 1, 9],
        [1, 1, 5]],

       [[7, 7, 1],
        [0, 6, 6],
        [6, 6, 0]]])

#### Crea una matriz de 10x10 con valores random y busca el mayor y el menor

In [46]:
x1 = np.random.randint(100, size=(10,10))
print (x1)
minimo=min(x1.min(axis=0))
maximo=max(x1.max(axis=0))
print (minimo,maximo)

[[45 35  5 68 11  9 32  1 43 17]
 [73 28 63 60 95 87 70 50  3 89]
 [41 41 56 63 41  4 50  3 24 75]
 [66 14 18 47 40 10 76 38 78 56]
 [15 63 46 80 87 35 66 96 82  0]
 [74 46 51 16 53 45 53  2  5 51]
 [80 10 30 31 30 38 26 28 21 39]
 [16 35 77 61  5 47 66 81 33 24]
 [ 8 59 45 55 28 13 90 84 24 63]
 [ 0 98  0 45 98 77  5 81 98 58]]
0 98


#### 14. Crea un vector de 30 elementos y busca la media.

In [58]:
x1=np.random.randint(0,100, 30)
resultado=sum(x1)/x1.size
print (x1,x1.size)
print (resultado)

[35 71 42 55 32 78 89 78 47 46 48 75 77 49 67 60  4 51 59 34 92  3 66 38
 83 26 51 92 64 96] 30
56.93333333333333


#### 15. Crea una matriz cuadrada con unos en los bordes 

In [67]:
x1=np.zeros((3,3))

x1[0]

array([0., 0., 0.])

#### A una matriz de 5x5 de unos añadele un borde de dos filas de 0's

#### 17. cual es el resultado de cada linea

```python
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
```

nan


#### 18. Crea una matriz de 5x5 con valores de 1 a 4 en la diagonal por debajo de la principal

In [ ]:
x1=np.zeros((3,3),k=-1)

#### 19. Crea una matriz de 8x8 con valores alternados 0,1

In [71]:
zeros=np.zeros((3,3))
zeros[]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 20. si una matriz es de 6x7x8 cual es el índice (x,y,z) del elemento 100?

#### 21. Usando la funcion tile, crea una matriz de 8x8 con plantilla [0,1],[1,0]

#### 22. Normaliza una matriz de 5x5  usando la media y desviación típica

#### 23. Crear un tipo de datos a medida np.dtype para un (R,G,B) de un byte

#### 24. Multiplicar una matriz de 5x3 por una de 3x2 

In [135]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
b=np.array([[1, 2], [3, 4], [5,6]])
c=a @ b
print (c)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. De un vector de 11 elementos negar los que estan entre la posición 3 y 8

In [90]:
x1=np.arange(1,11)
print(x1)
(x1[3:7]*-1)

[ 1  2  3  4  5  6  7  8  9 10]


#### 26. Cual es la salida del siguiente script

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
9
#(0+-1)+(1+-1)+(2+-1)+(3+-1)+(4+-1)+(5+-1)
from numpy import *
```

In [93]:
9

9

#### 27. Sea Z un vector de enteros de 10 elementos, ¿qué expresiones son legales?

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [95]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

NameError: name 'Z' is not defined

#### 28.¿Qué retorna cada expresión?

```python
np.array(0) / np.array(0) ---->nan
np.array(0) // np.array(0) ---->0
np.array([np.nan]).astype(int).astype(float)---> no se lo que devuelve exactamente pero... esta convirtiendo la cadena nan a entero y luego ese entero a float
```

#### 29. redondea a 0 un vector de elementos float

#### 30. Encuentra los elementos comunes entre dos vectores unidimensionales (interseción)

#### 31. desactiva los warnings (aunque mejor dejarlos)

In [ ]:
python -W ignore



#### 32. esto es verdadero y como se lee

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. con numpy consigue la fecha de ayer,hoy y mañana

In [114]:
yesterday=np.datetime64('today')-np.timedelta64(1, 'D')
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1, 'D')
print (yesterday ," ", today ," ", tomorrow)

2019-09-26   2019-09-27   2019-09-28


#### 34. Carga en un vector los dias del mes de julio

In [115]:
np.timedelta64(5, 'M')

numpy.timedelta64(5,'M')

#### 35. con tres vectores (A,B,C) consigue ((A+B)\*(-A/2)) en el vector A (★★☆)

In [125]:
A=np.arange(1,11)
B=np.arange(56,66)
C=np.arange(3,13)
A=((A+B)*(-A/C))
print(A)

[-19.         -29.5        -36.6        -42.         -46.42857143
 -50.25       -53.66666667 -56.8        -59.72727273 -62.5       ]


#### 36. De un vector de valores float consigue su parte entera de 5 formas diferentes.

#### 37. imprime una matriz de 5x5 donde cada fila tome valores entre 0 y 4

#### 38. Usando este generador construye un vector de floats
```python
def generate():
    for x in range(10):
        yield x
```

#### 39. Construye un vector de 10 elementos con valores balanceados entre 0 y 1 ambos excluidos

#### 40. Crea un vector aleatorio de 10 elementos ordenados

#### 41. intenta sumar los elementos de un vector de usando sum y reduce

#### 42. Convierte un vector en inmutable

#### 43. crea una matriz de 5x5 de coordenadas (x,y) float. debe ser rellenado con valores entre 0 y 1 tanto en x como en y

#### 44. Crea un array estructurado representando posicion (x,y) y color (r,g,b)

####  45. Convierte un array float 32bits en entero sin copiar el array

#### 46. Lee el siguiente fichero en un numpy array:
```python
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
```

#### 47. Imprime la diagonal de un producto de matrices de 5x5

#### 48. Dada una matriz de 5x5x3 y otra de 5x5 imprimir la multiplicación

#### 49. Intercambia dos filas de una matriz de 5x5

#### 50 dado dos vectores A y B de 10 elementos sacar su producto matricial